name: build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  publish-to-gallery:    
    name: "Publish to gallery"
    runs-on: ubuntu-latest
    #environment:
    #  name: "PowerShellGallery"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build and publish      
      shell: pwsh
      run: |             
        $newScriptInfo = @{
          Path = 'Update-InstalledModules.ps1'
          Version = '1.0.0'
          Author = 'arnab-roy-chowdhury'
          Description = "Update installed modules"
        }
        Update-ScriptFileInfo @newScriptInfo -Force
        Test-ScriptFileInfo -Path Update-InstalledModules.ps1
        



#$newScriptInfo = @{
#          Path = 'Update-InstalledModules.ps1'
#          Version = '1.0.0'
#          Author = 'arnab-roy-chowdhury'
#          Description = "Update installed modules"
#        }
#        New-ScriptFileInfo @newScriptInfo   

# ./build.ps1 -Path /tmp/samplemodule
# Publish-Module -Path /tmp/samplemodule -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -Verbose

#Publish-Script -Path D:\ScriptSharingDemo\Demo-Script.ps1 -Repository LocalRepo1
#Find-Script -Repository LocalRepo1 -Name "Demo-Script"